### ISSUE TITLE
Request: White List for Users

### ISSUE THREAD

**Issue by eigentlichich** [dscovr/pyinstamation#19]
Hey is there a way to whitelist some users that the bot isn't unfollowing them?

**Comment by Woile** [comment]
Could you explain it a bit further? Mostly the current behavior and your expected behavior.

Thanks!

**Comment by eigentlichich** [comment]
Thought about a way, that the bot doesn't unfollow specific users which I can add in a List. But it looks like the ignore_users List does exactly that. Sorry for the disturbance 😁

**Comment by Woile** [comment]
Cool!
